FROM node:alpine

# RUN mkdir -p /usr/src/app
# RUN chmod -R 777 /usr/src/app

WORKDIR /usr/src/app

COPY ./package.json ./

RUN npm install

COPY ./ ./

ENV CHOKIDAR_USEPOLLING=true

CMD ["npm", "run", "start"]